rules:
  - Rule1
  - Rule2
  - Rule3
  - Rule4
  - Rule5
staff:
  - Staff1
  - Staff2
  - Staff3
discord: https://discord.gg/3fW85m6
website: Coming Soon
event: Sorry, no events right now
reportusage: Do "/report <PlayerName>" to report someone