name: JustAnotherBanPlugin
version: ${project.version}
main: tolley.jabp.Main
api-version: 1.13
authors: [Tolley]
description: Just Another Ban Plugin
commands:
  punish:
    description: Opens up the punish GUI
    usage: /punish <USERNAME>
    aliases: [p, pun]
    permission: jabp.punish
  playerinfo:
    description: Gets information on a player
    usage: /playerinfo <USERNAME>
    aliases: [pi]
    permission: jabp.playerinfo
  userinterface:
    description: Opens up the punish GUI
    usage: /userinterface <USERNAME>
    aliases: [ui]
    permission: jabp.ui
permissions:
  jabp.punish:
    description: Allows /punish command
    default: op
  jabp.playerinfo:
    description: Allows /playerinfo command
    default: op
  jabp.receiveStaffMessages:
    description: Allows a player to recieve staff messages.
    default: op
  jabp.ui:
    description: Allows /userinterface command.
    default: op
  jabp.*:
    description: Allows all JustAnotherBanPlugin permissions
    default: op
    children:
      jabp.punish: true
      jabp.playerinfo: true
      jabp.receiveStaffMessages: true